/**
 * SLEEPER ANALYTICS SUITE - MOCK & FALLBACK DATASET
 * Realistic NFL Championship Fantasy Matchup with full rosters, bench, and variance parameters.
 */

export const MOCK_LEAGUE_INFO = {
  league_id: "demo_championship_league_2025",
  name: "Apex Fantasy Quantitative League",
  season: "2025",
  status: "in_season",
  total_rosters: 12,
  scoring_settings: {
    rec: 1.0, // PPR
    pass_td: 4.0,
    pass_yd: 0.04,
    rush_td: 6.0,
    rush_yd: 0.1,
    rec_td: 6.0,
    rec_yd: 0.1,
    pass_int: -2.0,
    fumble_lost: -2.0
  },
  roster_positions: ["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "K", "DEF", "BN", "BN", "BN", "BN", "BN", "BN"]
};

export const MOCK_USERS = [
  {
    user_id: "user_alpha_01",
    username: "QuantumChampion",
    display_name: "Quantum Blitz",
    avatar: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='120' height='120'><defs><linearGradient id='qbg' x1='0%25' y1='0%25' x2='100%25' y2='100%25'><stop offset='0%25' stop-color='%230f172a'/><stop offset='100%25' stop-color='%231e1b4b'/></linearGradient><linearGradient id='qbolt' x1='0%25' y1='0%25' x2='100%25' y2='100%25'><stop offset='0%25' stop-color='%2338bdf8'/><stop offset='50%25' stop-color='%23818cf8'/><stop offset='100%25' stop-color='%23c084fc'/></linearGradient><filter id='glow'><feGaussianBlur stdDeviation='3' result='coloredBlur'/><feMerge><feMergeNode in='coloredBlur'/><feMergeNode in='SourceGraphic'/></feMerge></filter></defs><rect width='120' height='120' rx='28' fill='url(%23qbg)' stroke='%2338bdf8' stroke-width='2.5'/><circle cx='60' cy='60' r='42' fill='none' stroke='rgba(56,189,248,0.2)' stroke-width='2' stroke-dasharray='4,4'/><path d='M66 22 L38 62 L58 62 L52 98 L82 54 L62 54 Z' fill='url(%23qbolt)' filter='url(%23glow)'/></svg>"
  },
  {
    user_id: "user_rival_02",
    username: "GridironWhale",
    display_name: "Apex Predators",
    avatar: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 120 120' width='120' height='120'><defs><linearGradient id='apbg' x1='0%25' y1='0%25' x2='100%25' y2='100%25'><stop offset='0%25' stop-color='%2318181b'/><stop offset='100%25' stop-color='%23450a0a'/></linearGradient><linearGradient id='aplion' x1='0%25' y1='0%25' x2='100%25' y2='100%25'><stop offset='0%25' stop-color='%23f59e0b'/><stop offset='50%25' stop-color='%23ef4444'/><stop offset='100%25' stop-color='%23b91c1c'/></linearGradient><filter id='apglow'><feGaussianBlur stdDeviation='3' result='coloredBlur'/><feMerge><feMergeNode in='coloredBlur'/><feMergeNode in='SourceGraphic'/></feMerge></filter></defs><rect width='120' height='120' rx='28' fill='url(%23apbg)' stroke='%23ef4444' stroke-width='2.5'/><path d='M60 24 L72 40 L88 36 L82 52 L96 62 L80 72 L84 88 L68 82 L60 96 L52 82 L36 88 L40 72 L24 62 L38 52 L32 36 L48 40 Z' fill='none' stroke='rgba(245,158,11,0.3)' stroke-width='2'/><path d='M60 32 L68 48 L82 46 L76 60 L88 70 L72 76 L74 90 L60 82 L46 90 L48 76 L32 70 L44 60 L38 46 L52 48 Z' fill='url(%23aplion)' filter='url(%23apglow)'/></svg>"
  }
];

export const MOCK_PLAYERS_DB = {
  // User Team Starters (Quantum Blitz)
  "p_josh_allen": {
    player_id: "p_josh_allen",
    full_name: "Josh Allen",
    first_name: "Josh",
    last_name: "Allen",
    position: "QB",
    team: "BUF",
    opponent: "vs BAL",
    points: 22.8,
    projected_points: 22.8,
    projected_pts: 22.8,
    floor: 14.5,
    floor10: 14.5,
    ceiling: 32.4,
    ceiling90: 32.4,
    variance: 0.24,
    skew: 0.9,
    status: "Active",
    game_status: "Sun 4:25 PM vs BAL",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/4984.jpg"
  },
  "p_cmc": {
    player_id: "p_cmc",
    full_name: "Christian McCaffrey",
    first_name: "Christian",
    last_name: "McCaffrey",
    position: "RB",
    team: "SF",
    opponent: "@ LAR",
    depth_chart_order: 1,
    points: 19.4,
    projected_points: 19.4,
    projected_pts: 19.4,
    floor: 12.0,
    floor10: 12.0,
    ceiling: 28.6,
    ceiling90: 28.6,
    variance: 0.35,
    skew: 1.5,
    status: "Inactive",
    game_status: "OUT - Achilles Tendinitis",
    injury_status: "OUT",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/4034.jpg"
  },
  "p_deandre_swift": {
    player_id: "p_deandre_swift",
    full_name: "D'Andre Swift",
    first_name: "D'Andre",
    last_name: "Swift",
    position: "RB",
    team: "CHI",
    opponent: "@ DET",
    points: 13.2,
    projected_points: 13.2,
    projected_pts: 13.2,
    floor: 6.8,
    floor10: 6.8,
    ceiling: 21.0,
    ceiling90: 21.0,
    variance: 0.40,
    skew: 1.5,
    status: "Active",
    game_status: "Sun 1:00 PM @ DET",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/6790.jpg"
  },
  "p_amonra": {
    player_id: "p_amonra",
    full_name: "Amon-Ra St. Brown",
    first_name: "Amon-Ra",
    last_name: "St. Brown",
    position: "WR",
    team: "DET",
    opponent: "vs CHI",
    points: 16.9,
    projected_points: 16.9,
    projected_pts: 16.9,
    floor: 10.5,
    floor10: 10.5,
    ceiling: 24.8,
    ceiling90: 24.8,
    variance: 0.30,
    skew: 1.1,
    status: "Active",
    game_status: "Sun 1:00 PM vs CHI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/7553.jpg"
  },
  "p_justin_jefferson": {
    player_id: "p_justin_jefferson",
    full_name: "Justin Jefferson",
    first_name: "Justin",
    last_name: "Jefferson",
    position: "WR",
    team: "MIN",
    opponent: "@ GB",
    points: 17.5,
    projected_points: 17.5,
    projected_pts: 17.5,
    floor: 9.8,
    floor10: 9.8,
    ceiling: 26.5,
    ceiling90: 26.5,
    variance: 0.36,
    skew: 1.5,
    status: "Active",
    game_status: "Sun 1:00 PM @ GB",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/6794.jpg"
  },
  "p_sam_laporta": {
    player_id: "p_sam_laporta",
    full_name: "Sam LaPorta",
    first_name: "Sam",
    last_name: "LaPorta",
    position: "TE",
    team: "DET",
    opponent: "vs CHI",
    points: 11.4,
    projected_points: 11.4,
    projected_pts: 11.4,
    floor: 5.2,
    floor10: 5.2,
    ceiling: 18.0,
    ceiling90: 18.0,
    variance: 0.42,
    skew: 1.8,
    status: "Active",
    game_status: "Sun 1:00 PM vs CHI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/9226.jpg"
  },
  "p_devonta_smith": {
    player_id: "p_devonta_smith",
    full_name: "DeVonta Smith",
    first_name: "DeVonta",
    last_name: "Smith",
    position: "WR",
    team: "PHI",
    opponent: "vs DAL",
    points: 13.8,
    projected_points: 13.8,
    projected_pts: 13.8,
    floor: 7.0,
    floor10: 7.0,
    ceiling: 22.1,
    ceiling90: 22.1,
    variance: 0.42,
    skew: 1.8,
    status: "Active",
    game_status: "Sun 4:25 PM vs DAL",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/7564.jpg"
  },
  "p_brandon_aubrey": {
    player_id: "p_brandon_aubrey",
    full_name: "Brandon Aubrey",
    first_name: "Brandon",
    last_name: "Aubrey",
    position: "K",
    team: "DAL",
    opponent: "@ PHI",
    points: 8.5,
    projected_points: 8.5,
    projected_pts: 8.5,
    floor: 4.0,
    floor10: 4.0,
    ceiling: 14.0,
    ceiling90: 14.0,
    variance: 0.32,
    skew: 1.1,
    status: "Active",
    game_status: "Sun 4:25 PM @ PHI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/9510.jpg"
  },
  "p_baltimore_def": {
    player_id: "p_baltimore_def",
    full_name: "Baltimore Ravens",
    first_name: "Baltimore",
    last_name: "Ravens",
    position: "DEF",
    team: "BAL",
    opponent: "@ BUF",
    points: 7.2,
    projected_points: 7.2,
    projected_pts: 7.2,
    floor: 2.0,
    floor10: 2.0,
    ceiling: 15.0,
    ceiling90: 15.0,
    variance: 0.48,
    skew: 1.4,
    status: "Active",
    game_status: "Sun 4:25 PM @ BUF",
    injury_status: null,
    avatar: "https://sleepercdn.com/images/v2/logos/nfl/bal.png"
  },

  // User Bench (Quantum Blitz)
  "p_malik_nabers": {
    player_id: "p_malik_nabers",
    full_name: "Malik Nabers",
    first_name: "Malik",
    last_name: "Nabers",
    position: "WR",
    team: "NYG",
    opponent: "vs WAS",
    points: 15.6,
    projected_points: 15.6,
    projected_pts: 15.6,
    floor: 8.0,
    floor10: 8.0,
    ceiling: 26.8,
    ceiling90: 26.8,
    variance: 0.50,
    skew: 2.2,
    status: "Active",
    game_status: "Sun 1:00 PM vs WAS",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/11560.jpg"
  },
  "p_brock_bowers": {
    player_id: "p_brock_bowers",
    full_name: "Brock Bowers",
    first_name: "Brock",
    last_name: "Bowers",
    position: "TE",
    team: "LV",
    opponent: "vs DEN",
    points: 13.2,
    projected_points: 13.2,
    projected_pts: 13.2,
    floor: 7.4,
    floor10: 7.4,
    ceiling: 21.2,
    ceiling90: 21.2,
    variance: 0.42,
    skew: 1.8,
    status: "Active",
    game_status: "Sun 4:05 PM vs DEN",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/11566.jpg"
  },
  "p_cj_stroud": {
    player_id: "p_cj_stroud",
    full_name: "C.J. Stroud",
    first_name: "C.J.",
    last_name: "Stroud",
    position: "QB",
    team: "HOU",
    opponent: "vs IND",
    points: 19.2,
    projected_points: 19.2,
    projected_pts: 19.2,
    floor: 12.8,
    floor10: 12.8,
    ceiling: 27.2,
    ceiling90: 27.2,
    variance: 0.28,
    skew: 1.1,
    status: "Active",
    game_status: "Sun 1:00 PM vs IND",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/9758.jpg"
  },
  "p_jaxon_smith": {
    player_id: "p_jaxon_smith",
    full_name: "Jaxon Smith-Njigba",
    first_name: "Jaxon",
    last_name: "Smith-Njigba",
    position: "WR",
    team: "SEA",
    opponent: "@ ARI",
    points: 12.4,
    projected_points: 12.4,
    projected_pts: 12.4,
    floor: 7.2,
    floor10: 7.2,
    ceiling: 19.5,
    ceiling90: 19.5,
    variance: 0.38,
    skew: 1.5,
    status: "Active",
    game_status: "Sun 4:05 PM @ ARI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/9493.jpg"
  },
  "p_zach_charbonnet": {
    player_id: "p_zach_charbonnet",
    full_name: "Zach Charbonnet",
    first_name: "Zach",
    last_name: "Charbonnet",
    position: "RB",
    team: "SEA",
    opponent: "@ ARI",
    points: 8.2,
    projected_points: 8.2,
    projected_pts: 8.2,
    floor: 3.8,
    floor10: 3.8,
    ceiling: 14.8,
    ceiling90: 14.8,
    variance: 0.55,
    skew: 2.1,
    status: "Active",
    game_status: "Sun 4:05 PM @ ARI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/9221.jpg"
  },

  // Opponent Starters (Apex Predators)
  "p_lamar_jackson": {
    player_id: "p_lamar_jackson",
    full_name: "Lamar Jackson",
    first_name: "Lamar",
    last_name: "Jackson",
    position: "QB",
    team: "BAL",
    opponent: "@ BUF",
    points: 21.6,
    projected_points: 21.6,
    projected_pts: 21.6,
    floor: 13.8,
    floor10: 13.8,
    ceiling: 30.5,
    ceiling90: 30.5,
    variance: 0.30,
    skew: 1.2,
    status: "Active",
    game_status: "Sun 4:25 PM @ BUF",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/4881.jpg"
  },
  "p_saquon_barkley": {
    player_id: "p_saquon_barkley",
    full_name: "Saquon Barkley",
    first_name: "Saquon",
    last_name: "Barkley",
    position: "RB",
    team: "PHI",
    opponent: "vs DAL",
    points: 17.2,
    projected_points: 17.2,
    projected_pts: 17.2,
    floor: 10.5,
    floor10: 10.5,
    ceiling: 25.5,
    ceiling90: 25.5,
    variance: 0.38,
    skew: 1.6,
    status: "Active",
    game_status: "Sun 4:25 PM vs DAL",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/4866.jpg"
  },
  "p_breece_hall": {
    player_id: "p_breece_hall",
    full_name: "Breece Hall",
    first_name: "Breece",
    last_name: "Hall",
    position: "RB",
    team: "NYJ",
    opponent: "vs MIA",
    points: 14.5,
    projected_points: 14.5,
    projected_pts: 14.5,
    floor: 8.5,
    floor10: 8.5,
    ceiling: 22.5,
    ceiling90: 22.5,
    variance: 0.40,
    skew: 1.7,
    status: "Active",
    game_status: "Sun 1:00 PM vs MIA",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/8155.jpg"
  },
  "p_ceedee_lamb": {
    player_id: "p_ceedee_lamb",
    full_name: "CeeDee Lamb",
    first_name: "CeeDee",
    last_name: "Lamb",
    position: "WR",
    team: "DAL",
    opponent: "@ PHI",
    points: 17.0,
    projected_points: 17.0,
    projected_pts: 17.0,
    floor: 10.2,
    floor10: 10.2,
    ceiling: 25.8,
    ceiling90: 25.8,
    variance: 0.35,
    skew: 1.4,
    status: "Active",
    game_status: "Sun 4:25 PM @ PHI",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/6786.jpg"
  },
  "p_jamarr_chase": {
    player_id: "p_jamarr_chase",
    full_name: "Ja'Marr Chase",
    first_name: "Ja'Marr",
    last_name: "Chase",
    position: "WR",
    team: "CIN",
    opponent: "vs PIT",
    points: 15.8,
    projected_points: 15.8,
    projected_pts: 15.8,
    floor: 8.5,
    floor10: 8.5,
    ceiling: 24.5,
    ceiling90: 24.5,
    variance: 0.38,
    skew: 1.6,
    status: "Active",
    game_status: "Sun 1:00 PM vs PIT",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/7564.jpg"
  },
  "p_travis_kelce": {
    player_id: "p_travis_kelce",
    full_name: "Travis Kelce",
    first_name: "Travis",
    last_name: "Kelce",
    position: "TE",
    team: "KC",
    opponent: "@ LAC",
    points: 11.2,
    projected_points: 11.2,
    projected_pts: 11.2,
    floor: 5.5,
    floor10: 5.5,
    ceiling: 18.0,
    ceiling90: 18.0,
    variance: 0.42,
    skew: 1.6,
    status: "Active",
    game_status: "Sun 4:25 PM @ LAC",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/1466.jpg"
  },
  "p_niko_collins": {
    player_id: "p_niko_collins",
    full_name: "Nico Collins",
    first_name: "Nico",
    last_name: "Collins",
    position: "WR",
    team: "HOU",
    opponent: "vs IND",
    points: 13.1,
    projected_points: 13.1,
    projected_pts: 13.1,
    floor: 6.8,
    floor10: 6.8,
    ceiling: 21.0,
    ceiling90: 21.0,
    variance: 0.40,
    skew: 1.7,
    status: "Active",
    game_status: "Sun 1:00 PM vs IND",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/7569.jpg"
  },
  "p_justin_tucker": {
    player_id: "p_justin_tucker",
    full_name: "Justin Tucker",
    first_name: "Justin",
    last_name: "Tucker",
    position: "K",
    team: "BAL",
    opponent: "@ BUF",
    points: 7.5,
    projected_points: 7.5,
    projected_pts: 7.5,
    floor: 3.0,
    floor10: 3.0,
    ceiling: 12.5,
    ceiling90: 12.5,
    variance: 0.35,
    skew: 1.1,
    status: "Active",
    game_status: "Sun 4:25 PM @ BUF",
    injury_status: null,
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/1264.jpg"
  },
  "p_sf_def": {
    player_id: "p_sf_def",
    full_name: "San Francisco 49ers",
    first_name: "San Francisco",
    last_name: "49ers",
    position: "DEF",
    team: "SF",
    opponent: "@ LAR",
    points: 6.2,
    projected_points: 6.2,
    projected_pts: 6.2,
    floor: 1.0,
    floor10: 1.0,
    ceiling: 13.0,
    ceiling90: 13.0,
    variance: 0.52,
    skew: 1.4,
    status: "Active",
    game_status: "Sun 4:05 PM @ LAR",
    injury_status: null,
    avatar: "https://sleepercdn.com/images/v2/logos/nfl/sf.png"
  }
};

export const MOCK_ROSTERS = [
  {
    roster_id: 1,
    owner_id: "user_alpha_01",
    league_id: "demo_championship_league_2025",
    starters: [
      "p_josh_allen",
      "p_cmc",
      "p_deandre_swift",
      "p_amonra",
      "p_justin_jefferson",
      "p_sam_laporta",
      "p_devonta_smith",
      "p_brandon_aubrey",
      "p_baltimore_def"
    ],
    players: [
      "p_josh_allen",
      "p_cmc",
      "p_deandre_swift",
      "p_amonra",
      "p_justin_jefferson",
      "p_sam_laporta",
      "p_devonta_smith",
      "p_brandon_aubrey",
      "p_baltimore_def",
      "p_malik_nabers",
      "p_brock_bowers",
      "p_cj_stroud",
      "p_jaxon_smith",
      "p_zach_charbonnet"
    ],
    settings: {
      wins: 11,
      losses: 3,
      fpts: 1845.2,
      fpts_against: 1612.4
    }
  },
  {
    roster_id: 2,
    owner_id: "user_rival_02",
    league_id: "demo_championship_league_2025",
    starters: [
      "p_lamar_jackson",
      "p_saquon_barkley",
      "p_breece_hall",
      "p_ceedee_lamb",
      "p_jamarr_chase",
      "p_travis_kelce",
      "p_niko_collins",
      "p_justin_tucker",
      "p_sf_def"
    ],
    players: [
      "p_lamar_jackson",
      "p_saquon_barkley",
      "p_breece_hall",
      "p_ceedee_lamb",
      "p_jamarr_chase",
      "p_travis_kelce",
      "p_niko_collins",
      "p_justin_tucker",
      "p_sf_def"
    ],
    settings: {
      wins: 10,
      losses: 4,
      fpts: 1812.8,
      fpts_against: 1640.1
    }
  }
];

export const MOCK_MATCHUPS = [
  {
    roster_id: 1,
    matchup_id: 1,
    starters: [
      "p_josh_allen",
      "p_cmc",
      "p_deandre_swift",
      "p_amonra",
      "p_justin_jefferson",
      "p_sam_laporta",
      "p_devonta_smith",
      "p_brandon_aubrey",
      "p_baltimore_def"
    ],
    players: [
      "p_josh_allen",
      "p_cmc",
      "p_deandre_swift",
      "p_amonra",
      "p_justin_jefferson",
      "p_sam_laporta",
      "p_devonta_smith",
      "p_brandon_aubrey",
      "p_baltimore_def",
      "p_malik_nabers",
      "p_brock_bowers",
      "p_cj_stroud",
      "p_jaxon_smith",
      "p_zach_charbonnet"
    ],
    custom_points: null,
    points: 0 // pre-game simulation
  },
  {
    roster_id: 2,
    matchup_id: 1,
    starters: [
      "p_lamar_jackson",
      "p_saquon_barkley",
      "p_breece_hall",
      "p_ceedee_lamb",
      "p_jamarr_chase",
      "p_travis_kelce",
      "p_niko_collins",
      "p_justin_tucker",
      "p_sf_def"
    ],
    players: [
      "p_lamar_jackson",
      "p_saquon_barkley",
      "p_breece_hall",
      "p_ceedee_lamb",
      "p_jamarr_chase",
      "p_travis_kelce",
      "p_niko_collins",
      "p_justin_tucker",
      "p_sf_def"
    ],
    custom_points: null,
    points: 0
  }
];

export const MOCK_FREE_AGENTS_DB = {
  "fa_jordan_mason": {
    player_id: "fa_jordan_mason",
    full_name: "Jordan Mason",
    first_name: "Jordan",
    last_name: "Mason",
    position: "RB",
    team: "SF",
    depth_chart_order: 2,
    opponent: "@ LAR",
    projected_pts: 4.8,
    projected_points: 4.8,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/8212.jpg"
  },
  "fa_khalil_shakir": {
    player_id: "fa_khalil_shakir",
    full_name: "Khalil Shakir",
    first_name: "Khalil",
    last_name: "Shakir",
    position: "WR",
    team: "BUF",
    opponent: "vs ARI",
    projected_pts: 12.8,
    projected_points: 12.8,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/8138.jpg"
  },
  "fa_trey_benson": {
    player_id: "fa_trey_benson",
    full_name: "Trey Benson",
    first_name: "Trey",
    last_name: "Benson",
    position: "RB",
    team: "ARI",
    opponent: "@ BUF",
    projected_pts: 8.6,
    projected_points: 8.6,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/11560.jpg"
  },
  "fa_chuba_hubbard": {
    player_id: "fa_chuba_hubbard",
    full_name: "Chuba Hubbard",
    first_name: "Chuba",
    last_name: "Hubbard",
    position: "RB",
    team: "CAR",
    opponent: "@ NO",
    projected_pts: 11.8,
    projected_points: 11.8,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/7564.jpg"
  },
  "fa_demarcus_robinson": {
    player_id: "fa_demarcus_robinson",
    full_name: "Demarcus Robinson",
    first_name: "Demarcus",
    last_name: "Robinson",
    position: "WR",
    team: "LAR",
    opponent: "@ DET",
    projected_pts: 10.6,
    projected_points: 10.6,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/3199.jpg"
  },
  "fa_colby_parkinson": {
    player_id: "fa_colby_parkinson",
    full_name: "Colby Parkinson",
    first_name: "Colby",
    last_name: "Parkinson",
    position: "TE",
    team: "LAR",
    opponent: "@ DET",
    projected_pts: 9.4,
    projected_points: 9.4,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/6826.jpg"
  },
  "fa_bucs_def": {
    player_id: "fa_bucs_def",
    full_name: "Tampa Bay Buccaneers",
    first_name: "Tampa Bay",
    last_name: "Buccaneers",
    position: "DEF",
    team: "TB",
    opponent: "vs WAS",
    projected_pts: 8.8,
    projected_points: 8.8,
    status: "Active",
    avatar: "https://sleepercdn.com/images/v2/icons/player_default.webp"
  },
  "fa_seahawks_def": {
    player_id: "fa_seahawks_def",
    full_name: "Seattle Seahawks",
    first_name: "Seattle",
    last_name: "Seahawks",
    position: "DEF",
    team: "SEA",
    opponent: "vs DEN",
    projected_pts: 8.4,
    projected_points: 8.4,
    status: "Active",
    avatar: "https://sleepercdn.com/images/v2/icons/player_default.webp"
  },
  "fa_sam_darnold": {
    player_id: "fa_sam_darnold",
    full_name: "Sam Darnold",
    first_name: "Sam",
    last_name: "Darnold",
    position: "QB",
    team: "MIN",
    opponent: "@ NYG",
    projected_pts: 16.2,
    projected_points: 16.2,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/4981.jpg"
  },
  "fa_matt_prater": {
    player_id: "fa_matt_prater",
    full_name: "Matt Prater",
    first_name: "Matt",
    last_name: "Prater",
    position: "K",
    team: "ARI",
    opponent: "@ BUF",
    projected_pts: 8.2,
    projected_points: 8.2,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/prater.jpg"
  },
  "fa_ray_davis": {
    player_id: "fa_ray_davis",
    full_name: "Ray Davis",
    first_name: "Ray",
    last_name: "Davis",
    position: "RB",
    team: "BUF",
    opponent: "vs ARI",
    projected_pts: 7.4,
    projected_points: 7.4,
    status: "Active",
    avatar: "https://sleepercdn.com/content/nfl/players/thumb/11565.jpg"
  }
};

export const MOCK_MASTER_PLAYERS_POOL = {
  ...MOCK_PLAYERS_DB,
  ...MOCK_FREE_AGENTS_DB
};

